### ISSUE TITLE
tipping banner should have close button

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#1273] opened 2019-03-08 22:31 UTC
## Description 
Tipping Banner on Android should have close (x) button to close tipping banner. Banner has a close (X) button on b-c.

## Steps to Reproduce 

   1. Navigate to a site and tap on BAT logo
   2. Tap on Send a Tip

## Actual result: 
Banner takes up entire screen, it's not entirely apparent how you can close it without actually tipping.
![bannernoX-pixel](https://user-images.githubusercontent.com/28145373/54059548-9116d200-41c7-11e9-80cf-61e5aebe8fe8.png)

## Expected result:
A close / X button to close tipping banner as there is on b-c.
![Screen Shot 2019-03-08 at 4 56 29 PM](https://user-images.githubusercontent.com/28145373/54059573-a0961b00-41c7-11e9-93e5-61184e3d0373.png)

## Issue reproduces how often: 
easily

## Issue happens on: 
   - Current Playstore version? no
   - Beta build? Rewards Beta

## Device Details:
   - Install Type(ARM, x86): all
   - Device(Phone, Tablet, Phablet): all
   - Android Version: all
   
## Brave version:
1.0.85 (BR_5)

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by LaurenWags** [comment] 2019-03-08 22:31
cc @srirambv @anthonypkeane

**Comment by anthonypkeane** [comment] 2019-03-08 23:27
@jamesmudgett the back button could be enough. Thoughts?

**Comment by NejcZdovc** [comment] 2019-03-09 05:46
closing as dupe of https://github.com/brave/browser-android-tabs/issues/1127

**Closed by NejcZdovc** 2019-03-09 05:46 UTC
Labels: QA/Test-plan-specified, QA/Yes, feature/BR
