### ISSUE TITLE
Brave crashes in a clean and upgraded profile of 1.5.5-rc2

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#2542] opened 2020-02-12 14:58 UTC
## Description 
Brave crashes in a clean and upgraded profile of 1.5.5-rc2

## Steps to reproduce 
Scenario 1: clean profile
   1. clean profile 1.5.5-rc2
   2. enable rewards via onboarding flow
   3. open a new tab from the hamburger menu (open 2 or 3 tabs, sometimes crash will happen at 2nd tab)
   4. If the crash doesn't happen at step3, then open a 4th new tab from the hamburger menu
   5. open hamburger menu and open setting->About brave 
   6. tap on the back button after viewing brave version brave crashes

Scenario 2: upgraded profile
  1. clean profile 1.5.4 enable rewards via on-boarding 
  2. upgrade to 1.5.5-rc2
  3. open a new tab from the hamburger menu
  4. open a second new tab from hamburger menu - some times crash happens in the 2nd tab itself
  5. open a 3rd new tab from hamburger menu - NTP SI is shown
  6. open hamburger menu and click on settings - brave crashes

## Actual result 
Brave crashes in a clean and upgraded profile of 1.5.5-rc2

https://drive.google.com/open?id=1ybi88jBbQaZAAZFBZs2Ef89hvtSzrpsd
https://drive.google.com/open?id=1xb6oADkG_6nPDXPjXGpllD8vblE8qC0-

## Expected result
Should not be any crash

## Issue reproduces how often 

Always
## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 5.1.1
   
## Brave version
1.5.5-rc2

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/legacy_qa @anthonypkeane @deeppandya

**Comment by LaurenWags** [comment] 2020-02-12 14:59
Reproduced Scenario 1 and 2 on LG Nexus 5 running Android 5.1 with 1.5.5.rc2.

**Comment by srirambv** [comment] 2020-02-12 15:01
Cant reproduce on OnePlus 6T with Android 10. https://bravesoftware.slack.com/archives/CQGTGBNH1/p1581519211274300?thread_ts=1581517074.271400&cid=CQGTGBNH1

**Comment by kjozwiak** [comment] 2020-02-13 03:01
@deeppandya was this fixed in https://github.com/brave/browser-android-tabs/releases/tag/v1.5.5RC3? I'm not seeing any PR associated with a crash under https://github.com/brave/browser-android-tabs/commits/base-79.0.3945.136 unless it was included in either https://github.com/brave/browser-android-tabs/pull/2544 or https://github.com/brave/browser-android-tabs/pull/2540.

**Comment by deeppandya** [comment] 2020-02-13 03:08
Fixed by https://github.com/brave/browser-android-tabs/pull/2545

**Closed by deeppandya** 2020-02-13 03:08 UTC
Labels: ARM, QA/Test-plan-specified, QA/Yes, crash, regression

**Comment by kjozwiak** [comment] 2020-02-13 04:12
Verification **PASSED** on `Samsung S10+` on `Android` using `1.5.5 RC3 CR: 79.0.3945.136` via https://github.com/brave/browser-android-tabs/releases/tag/v1.5.5RC3: 

* Verified the the original STR outlined under https://github.com/brave/browser-android-tabs/issues/2542#issue-564056760
* Verified that opening 15 new tabs via the `Hamburger Menu` didn't cause any crashes
* Verified that opening 10 new tabs via the "+" button via the toolbar didn't cause any crashes
* Verified that opening 15 new PT via the `Hamburger Menu` didn't cause any crashes
* Verified that opening 10 new PT via the "+" button via the toolbar didn't cause any crashes
* ensured that closing the ~50 tabs via `Close All Tabs` didn't cause any crashes
* ensured that all of the above cases also worked after upgrading from `1.5.4` --> `1.5.5`

Disclosure: I could never reproduce the original issue so @GeetaSarvadnya and @LaurenWags should go through the above with their older devices to ensure they're not experiencing any crashes.

**Comment by GeetaSarvadnya** [comment] 2020-02-13 04:28
Verification passed on Samsung Galaxy J3 version 5.1.1 running `BraveModernarm.apk 1.5.5-rc3`
 - Verified both clean and upgraded profile, observed there is no crash.

**Comment by srirambv** [comment] 2020-02-13 04:58
Verification passed on Samsung Tab A with Android 9.0 running 1.5.5 RC3 x64 build
- Verified opening >15 tabs doesn't crash the browser
- Verified opening >15 private tabs doesn't crash the browser
- Verified opening a combination of normal and private tabs doesn't crash the browser
