### ISSUE TITLE
Strings not translated for Ads 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#982] opened 2019-01-19 06:53 UTC
## Description 
Strings not translated for Ads 

## Steps to Reproduce 

   1. Install 1.0.74
   2. Enable rewards
   3. Enable ads, check settings, strings not translated

## Actual result: 
![image](https://user-images.githubusercontent.com/17010094/51423342-c39f4800-1be4-11e9-98ec-32804965b826.png)

## Expected result:
Should be translated

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version? NO
   - Beta build? Yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Phone
   - Android Version: 9.0
   
## Brave version:
1.0.74

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @SergeyZhukovsky @ryanml

**Comment by SergeyZhukovsky** [comment] 2019-01-19 23:41
@ryanml it's possible because we didn't pull latest brave-core, I'm going to pull the latest next week.

**Comment by ryanml** [comment] 2019-01-20 01:42
@Serg thank you. I'll hold off on cherry picking strings for now until you pull that in, it may fix a couple of the other string related issues as well

**Comment by btlechowski** [comment] 2019-01-22 00:52
Reproduced on Samsung s7 (ARM, Android 8.0.0), Brave v1.0.74
![982](https://user-images.githubusercontent.com/34715963/51505675-4cd29c80-1de8-11e9-8df9-2a97a45280b6.jpg)

**Comment by ryanml** [comment] 2019-01-28 18:15
Strings recently merged in, should be good to go:

cc: @SergeyZhukovsky

**Closed by ryanml** 2019-01-28 18:15 UTC
Labels: QA/Yes, bug/BR, bug/BR-wait_for_upstream
