### ISSUE TITLE
Default `Monthly Payment` is different in `Auto-Contribute` and `Auto-Contribute Settings` panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1161] opened 2019-02-19 18:52 UTC
## Description 
Default `Monthly Payment` is different in `Auto-Contribute` and `Auto-Contribute Settings` panel

## Steps to Reproduce 

   1. Cleam profile 1.0.81
   2. Enable rewards
   3.  Verify the Default `Monthly payment` in `Auto-Contribute` and `Auto-Contribute Settings` page

## Actual result: 
By default monthly payment is displayed as 20 BAT in `Auto-Contribute` panel and 10 BAT in `Auto-Contribute Settings`

https://drive.google.com/open?id=1GXIlHDvAaGVfVc56jKD_OYSpC3E-qedZ

## Expected result:
by default monthly payment should be same in both places 

## Issue reproduces how often: 
Always
## Issue happens on: 
   - Current Playstore version?no
   - Beta build?yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android Version: 5.1
   
## Brave version:
1.0.81

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by NejcZdovc** [comment] 2019-02-19 19:20
closing as dupe of https://github.com/brave/browser-android-tabs/issues/1141

**Closed by NejcZdovc** 2019-02-19 19:20 UTC
Labels: QA/Yes, bug/BR
