### ISSUE TITLE
non-ascii domain names are displayed in Punycode instead of Unicode 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#2290] opened 2019-11-13 17:24 UTC
## Description 
non-ascii domain names are displayed in Punycode instead of Unicode 

## Steps to reproduce 
TBA

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/68787742-17fe3300-0610-11ea-8130-a0a92725fde9.png)

## Expected result
Should show in Unicode

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? N/A

## Device details
   - Install type (ARM, x86): All
   - Device (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
GPS 

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by gdregalo** [comment] 2019-11-29 15:13
Duplicate of https://github.com/brave/browser-android-tabs/issues/2289.
A separate issue should be created for desktop.

**Closed by gdregalo** 2019-11-29 15:13 UTC
Labels: ARM, QA/Yes, release-notes/include

**Comment by srirambv** [comment] 2019-12-12 21:02
moving out of 1.6.1 as #2289 is marked for 1.6.2
