### ISSUE TITLE
Sample ad notification should only be triggered the first time ads is enabled

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1809] opened 2019-07-03 18:58 UTC
## Description 
Sample ad notification should only be triggered the first time ads is enabled

## Steps to reproduce 

   1. Install ads build
   2. Enable ads, view sample ad notification
   3. Disable ads and re-enable it, a second sample ad notification is shown

## Actual result 
Sample ad is shown every time ads are disabled and enabled

## Expected result
Sample ad notification should only be triggered the first time ads is enabled

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone (Huawei P20)
   - Android version: 8.1.0
   
## Brave version
1.1.0-6 ads build x64

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by tmancey** [comment] 2019-07-15 23:39
@srirambv Can you please retest this on the Play Store build as I believe this was resolved

**Comment by gdregalo** [comment] 2019-08-20 15:41
Couldn't reproduce it in `base-76.0.3809.111`.

**Comment by tmancey** [comment] 2019-08-20 16:21
@srirambv are you happy that we close this issue?

**Closed** 2019-08-21 14:10 UTC
Labels: QA/Yes, bug, bug/BR, bug/ads, release-notes/exclude

**Comment by srirambv** [comment] 2019-08-21 22:02
* Verification passed on OnePlust 6T with Android 9.0 running 1.3.0-beta-x64 build
  * Verified on a clean install, disable and re-enable ads doesn't trigger sample ad notification
  * Verified on upgrade, disable and re-enable ads doesn't trigger sample ad notification
