### ISSUE TITLE
Lion Icon No Reaction

### ISSUE THREAD

**Issue by MisterGlasses** [brave/browser-android-tabs#813] opened 2018-11-03 08:33 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
There are no reaction clicking the lion icon when I enable chrome duet since 1.59 version.

**Device Details:**
   - Install Type(ARM, x86):ARM
   - Device(Phone, Tablet, Phablet):Phone
   - Android Version: O
    
**Brave Version:1.59 1.60 1.61

**Is this an issue with Beta build?**

No
**Is this an issue in the currently released version?**

Yes
**Can this issue be consistently reproduced?**

Yes

**Screenshot if needed:**
![screenshot_20181103-163012](https://user-images.githubusercontent.com/27768847/47949960-34559300-df19-11e8-8db8-013697808550.jpg)

**Comment by eljuno** [comment] 2019-02-12 19:51
Duplicate of #900

**Closed** 2019-02-13 03:52 UTC
