### ISSUE TITLE
Verified check icon is NOT displayed in BR panel for DDG but it shows in AC table and Tips panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#2182] opened 2019-10-25 09:22 UTC
## Description 
Found while testing https://github.com/brave/browser-android-tabs/issues/2178

Verified check icon is NOT displayed in BR panel for DDG but it shows in AC table and Tips panel

## Steps to reproduce 

   1. Clean Profile 1.4.3-rc.2
   2. Add few verified pubs to AC table (DDG, Brave and https://www.youtube.com/watch?v=6ZKU67VF4y8)
   3. Open BR panel for each pub and make sure verified icon is displayed in the panel
   4. The verified icon is NOT displayed in BR panel for DDG (Refresh/open and close panel doesn't help)

## Actual result 
Verified check icon is NOT displayed in BR panel for DDG but it shows in AC table and Tips panel

![Screenshot_2019-10-25-14-37-33](https://user-images.githubusercontent.com/38657976/67559452-9f096b00-f736-11e9-9054-3eafcf41afc0.png)

![Screenshot_2019-10-25-14-37-23](https://user-images.githubusercontent.com/38657976/67559465-a466b580-f736-11e9-8ae1-8593b7dcf989.png)

## Expected result
For verified pubs, the verified icon should be displayed in BR panel

## Issue reproduces how often 

Always
## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 5.1.1
   
## Brave version

1.4.3-rc2
### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/legacy_qa @SergeyZhukovsky @anthonypkeane

**Comment by srirambv** [comment] 2019-10-25 11:33
Android never had the verified icon on panel. @anthonypkeane this should be done as part of 1.5.0

**Comment by samartnik** [comment] 2019-10-25 12:53
I believe it works on 1.4.0. The cause of problem is the same as in https://github.com/brave/browser-android-tabs/issues/2178
I thinks it needs to be fixed in 1.4.3

**Comment by srirambv** [comment] 2019-10-25 13:02
> I believe it works on 1.4.0. 

@samartnik  rewards panel doesn't have a verified icon on Android. We only show the red dot on a clean install and show numbers on notifications for 
* Grant availability
* Failed tipping
* Insufficient funds for auto contribution
* Successful auto contribution
* Server connection errors

**Closed** 2019-10-25 13:22 UTC
Labels: ARM, QA/Test-plan-specified, QA/Yes, bug, feature/rewards, regression

**Comment by srirambv** [comment] 2019-10-28 14:10
* Verification passed on OnePlus 6T with Android 9.0 running 1.4.3RC3 x64 build
