### ISSUE TITLE
`Auto Contribution` panel details are viewable when Rewards is set to OFF

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1010] opened 2019-01-21 10:24 UTC
## Description 
`Auto Contribution` panel details are viewable when Rewards is set to OFF

## Steps to Reproduce 

   1. Enable Rewards through `Learn More` 
   2. Disable Rewards (Turn off the Rewards switch)
   3. Click on `View Details` under Auto Contribution panel
   3. Auto Contribution details are viewable

## Actual result: 
`Auto Contribution` panel details are viewable when Rewards is set to OFF

## Expected result:
`Auto Contribution` details should not be shown when Rewards is set to OFF

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version? no
   - Beta build? Yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Android - Samsumg Galaxy J3
   - Android Version: 5.1
   
## Brave version:
1.0.74
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

**Comment by srirambv** [comment] 2019-01-21 10:37
Dupe of https://github.com/brave/browser-android-tabs/issues/1002

**Closed by srirambv** 2019-01-21 10:37 UTC
Labels: duplicate
