### ISSUE TITLE
copying & pasting address from dev menu doesn't work

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-android-tabs#1655] opened 2019-06-07 07:03 UTC
## Description 

Copying/Pasting crypto addresses from the dev menu doesn't work

## Steps to reproduce 

   1. install & launch `1.0.97 CR: 75.0.3770.67`
   2. access the `developer options` -> `QA Preferences`
   3. copy one of the addresses from the list and attempt to paste it somewhere

## Actual result 

Copying/Pasting addresses via `QA Preferences` doesn't work

## Expected result

Copying/Pasting addresses from `QA Preferences` should work as expected

## Issue reproduces how often 

100% reproducible using the above STR.

## Issue happens on 
   - Current Play Store version? `N/A`
   - Beta build? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device (Phone, Tablet, Phablet): `Pixel 2 XL`
   - Android version: `Android 9`
   
## Brave version

* `1.0.97 CR: 75.0.3770.67`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by kjozwiak** [comment] 2019-06-07 07:04
@srirambv can you prioritize this? We should get this fixed sooner than later as it will give QA more capability to debug/troubleshoot issues 👍

**Comment by GeetaSarvadnya** [comment] 2019-06-07 07:06
The issue is Reproducible in 1.0.97 verified on Samsung Galaxy J3 version 5.1.1

**Comment by srirambv** [comment] 2019-06-07 11:18
Cant reproduce on Huawei P20. Works just fine. Am able to copy paste in external application and on new tab. Marking as P3 to be fixed for next release. Not a blocker

**Comment by srirambv** [comment] 2019-06-07 13:05
Don't think this is an issue. If there is no address shown meaning empty text and if you still click it then it will show the message of copied to clipboard but there is nothing to copy. 

More info here https://bravesoftware.slack.com/archives/GAA4017R7/p1559912635195500

**Closed by srirambv** 2019-06-07 13:05 UTC
Labels: QA/Yes, bug, feature/settings, priority/P3

**Comment by btlechowski** [comment] 2019-06-07 13:46
If I enable rewards frist then I can copy the addresses.

**Comment by kjozwiak** [comment] 2019-06-07 15:18
Tried it a few times, working now 👍 I'm not sure why it didn't work before. I was seeing the address but it wasn't pasting. Tried it a few times with different users, working correctly.

Thanks for the double check @srirambv @btlechowski.
