### ISSUE TITLE
Enable rewards doesn't auto enable ads

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1694] opened 2019-06-13 20:30 UTC
## Description 
Enable rewards doesn't auto enable ads

## Steps to reproduce 

   1. Clean install 1.0.98
   2. Enable rewards via onboarding flow by tapping on `I'M IN!`
   3. Open rewards page, ads switch is turned off. You need to manually turn it on

## Actual result 
Enable rewards doesn't auto enable ads

## Expected result
Ads should auto enable when rewards is turned on for the first time

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? N/A
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone Huawei P20
   - Android version: 8.1.0
   
## Brave version
1.0.98 Ads build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by tmancey** [comment] 2019-06-13 22:42
Tested with @anthonypkeane and we both cannot reproduce, can you please provide a video

**Comment by srirambv** [comment] 2019-06-14 11:51
Ok found the correct steps to reproduce it
Scenario 1:
1. Clean install 
2. Open rewards page via hamburger menu
3. Join rewards
4. Ads is not enabled, auto-contribute enables automatically after 2 sec delay(current behaviour)

Recording: [scenario1.zip](https://github.com/brave/browser-android-tabs/files/3290489/scenario1.zip)

Scenario 2:
1. Clean install
2. Open BR Panel
3. Close the onboarding message
4. Open BR panel and join rewards
5. Open rewards page, ads is not turned on 

Recording: [scenario2.zip](https://github.com/brave/browser-android-tabs/files/3290488/scenario2.zip)

**Comment by btlechowski** [comment] 2019-06-18 22:03
Reproduced on BraveModernarm v1.1.0-brave-ads on Samsung s7. Reproduced both scenarios from: https://github.com/brave/browser-android-tabs/issues/1694#issuecomment-502079465

**Comment by tmancey** [comment] 2019-06-18 22:44
@btlechowski This should be fixed for the next build we send out tomorrow

**Comment by yachtcaptain23** [comment] 2019-06-19 23:24
Fixed by https://github.com/brave/browser-android-tabs/pull/1726

**Comment by GeetaSarvadnya** [comment] 2019-06-27 10:00
Scenario1 is still NOT fixed, hence reopening the issue.

**Comment by tmancey** [comment] 2019-07-03 11:41
@GeetaSarvadnya can you please raise a new ticket for scenario 1

**Closed by tmancey** 2019-07-03 11:41 UTC
Labels: QA/Yes, bug, bug/ads, priority/P2, release-notes/exclude

**Comment by GeetaSarvadnya** [comment] 2019-07-03 18:44
- Verification passed on Samsung Galaxy J3 version 5.1.1 running BraveModernarm `v1.1.0-brave-ads-6`
  - Verified the STR from the description
  - Logged a follow-up issue https://github.com/brave/browser-android-tabs/issues/1808
