### ISSUE TITLE
Lastpass integration

### ISSUE THREAD

**Issue by heinhuiz** [brave/browser-android-tabs#70] opened 2016-11-21 16:28 UTC
LastPass is available for the desktop version. Will it be integrated into the Android app also?

**Comment by SergeyZhukovsky** [comment] 2016-11-21 19:58
We are going to work on that very soon.

**Comment by heinhuiz** [comment] 2016-11-21 23:22
If that is as quick as your answer I would be more than pleased!

**Comment by pittfern** [comment] 2017-03-30 07:57
Brave is my new favorite browser! Thanks for the hard work, @brave-dev !

Just as a friendly side note, I would love to see LastPass integration in the mobile app for Android. How can I help make this happen? A quick search doesn't turn up much being done in the repository at the moment.

**Comment by travi** [comment] 2017-07-06 15:37
Is this still planned/in progress? I see that it is tied to a milestone that has already been closed, so it's hard to understand it's state. 

Love the browser, but this still makes it very inconvenient to use.

**Comment by SergeyZhukovsky** [comment] 2017-07-18 02:39
@travi LastPass works to me. Doesn't it for you?

**Comment by travi** [comment] 2017-07-18 02:49
works how? i've never seen a release that suggests that it should. 

the autofill prompt does not come up for me when i enter a password input like it does in other apps, including chrome. i even try forcing it to come up by clicking the persistent "notification" and it still does not come up. 

versions:
* android 6.0.1
* lastpass 4.2.762
* brave 1.0.24

if there is a way to get this working, i'd love to learn about it

**Comment by SergeyZhukovsky** [comment] 2017-07-18 12:48
@travi look at the video how it works on my devices(I tried on several):
https://drive.google.com/file/d/0B00h0ZE3nmZPMUNKRExrcTk0S0k/view?usp=sharing
Do you have a LastPass accessibility service enabled(when it is disabled it doesn't work on any other apps as well), it is on your device Settings->Accessibility->LastPass
I'm on the latest Brave and LastPass as well, the same versions as you.

**Comment by travi** [comment] 2017-07-18 13:19
Well, now i guess I'm disappointed that i waited so long to speak up. Your video shows exactly how i would expect it to work, but that does not happen for me. The accessibility feature you mention is turned on and auto fill works properly for all other apps. 

I've been a user ever since the tabs version of the app was released. At that point, i know others were reporting it not working and it sounded like a fundamental incompatibility, so I've just been waiting for it to be resolved. 

What other thoughts do you have beyond reinstalling both apps?

**Comment by SergeyZhukovsky** [comment] 2017-07-18 13:52
I just tried it on one device that had Brave installed from the beginning but never had  LastPass there, it works. @pittfern, @heinhuiz could you check on your devices?

**Comment by heinhuiz** [comment] 2017-07-18 14:34
Works fine for me too (same versions as @travi). Maybe you didn't give Usage access to Lastpass? Under Settings/Security.

**Comment by travi** [comment] 2017-07-18 14:56
usage access is also on. again, lastpass is working correctly with all of my other apps. is there a toggle anywhere for specifically interacting with brave?

**Comment by heinhuiz** [comment] 2017-07-18 15:20
Inside the Lastpass app, Settings / App fill / Edit app fill settings / Brave the checkmark Do not show fill window should be unchecked. 
I don't recall any other settings.

**Comment by travi** [comment] 2017-07-18 15:29
that was it! i really wonder how that ever got checked (it had a list of sites too). i swear i'd looked all over for a setting like that, but never found one.

thanks so much. this will greatly improve the experience of using brave for me!

**Comment by SergeyZhukovsky** [comment] 2017-07-18 15:32
Thank you @heinhuiz for the huge help with that. Enjoy @travi. I'm closing the ticket as the issue is resolved.

**Closed by SergeyZhukovsky** 2017-07-18 15:32 UTC
Labels: feature request

**Comment by travi** [comment] 2017-07-20 13:30
I'm still stumbling on others the are having problems. Not sure if it's worth some sort of communication. https://twitter.com/mgroves/status/888023160515428352

**Comment by SergeyZhukovsky** [comment] 2017-07-20 13:49
Thank you @travi. I responded to him as well. We will create a FAQ for that if we see significant number of customers with the problem.

**Comment by MightyCreak** [comment] 2019-04-17 01:19
I had to enable the legacy autofill system in LastPass in order to make it work with Brave. Is it normal?
