### ISSUE TITLE
Wallet summary says no tokens even when grant is claimed

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1190] opened 2019-02-26 04:36 UTC
## Description 
Wallet summary says no tokens even when grant is claimed

## Steps to Reproduce 

   1. Clean install new rewards build
   2. Join rewards via BR panel
   3. Claim grants via BR panel
   4. Open rewards page and open wallet details, shows `Sadly no tokens yet`

## Actual result: 
![screenshot_20190226-100404](https://user-images.githubusercontent.com/17010094/53387713-1f13e100-39ae-11e9-848c-a6bc81af91e7.png)

## Expected result:
Should only show the message when wallet is having 0 BAT

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version?
No
   - Beta build?
Yes
## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Phone
   - Android Version: 9.0
   
## Brave version:
1.0.83 (rewards build)

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by ryanml** [comment] 2019-02-28 19:20
Closing as a dupe of this one: https://github.com/brave/browser-android-tabs/issues/1213 

The problem right now is no items will show for the summary not just tokens

**Closed by ryanml** 2019-02-28 19:20 UTC
Labels: QA/Yes, bug/BR, priority/P3
