### ISSUE TITLE
tapping on sample ad notification is showing 'Unfortunately, Brave has stopped' message

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#1811] opened 2019-07-03 19:55 UTC
## Description 
Sample ad notification is showing 'Unfortunately, Brave has stopped' message on some Android versions. Originally reported with https://github.com/brave/browser-android-tabs/issues/1805#issuecomment-508168765 by @GeetaSarvadnya 

## Steps to reproduce 

   1. Install play store build, do not enable rewards
   2. Install 1.1.0-6 ads build
   3. Enable rewards from in-app notification
   4. Wait for sample ad notification to show up
   5. Quit browser and tap on the sample ad notification

## Actual result 
Get message:
![Screenshot_2019-07-03-15-34-24](https://user-images.githubusercontent.com/28145373/60621006-a0d7a900-9daa-11e9-80e8-aff5ead00c0f.png)

## Expected result
Brave will open and show expected page.

## Issue reproduces how often 
easily

## Issue happens on 
   - Current Play Store version? n/a
   - Beta build? yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): phone
   - Android version: Android 5.1
   
## Brave version
1.1.0 ads-6

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional information
Probably only an issue with earlier Android versions

**Comment by anthonypkeane** [comment] 2019-07-04 03:31
I've a Moto X on android 5.1 and I didn't get this bug.



![1811](https://user-images.githubusercontent.com/7606853/60637859-f32bc080-9dd0-11e9-8c25-e619176a3826.gif)

**Comment by anthonypkeane** [comment] 2019-07-04 03:34
I'm not seeing this when enabling from the Panel, but waiting for the modal now to test.

**Comment by tmancey** [comment] 2019-07-04 05:42
@anthonypkeane @LaurenWags Duplicate of #1805

**Closed** 2019-07-05 23:10 UTC
Labels: QA/Yes, bug

**Comment by GeetaSarvadnya** [comment] 2019-07-08 10:51
- Verification passed on Samsung Galaxy J3 version 5.1.1 running Bravemodernarm `1.1.0-brave-ads-8` build
