### ISSUE TITLE
Keep videos playing after switching tab, minimizing Brave, switching off display 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#160] opened 2017-02-27 08:36 UTC
From community user  https://community.brave.com/t/mobile-keep-videos-playing-after-switching-tab-minimizing-brave-switching-off-display/1441

> Currently, videos provided e.g. via youtube stop playing as soon as one either switches to a different tab inside Brave or minimizes the whole app or switches off the device's display 
Could this behaviour be changed so that videos keep on playing anyway in any of the scenarios described?

**Comment by AlexeyBarabash** [comment] 2017-11-07 09:29
Created a branch with a fix
https://github.com/AlexeyBarabash/browser-android-tabs/tree/VideoInBackground .

This fix will not be merged into the master. The main reason: a mobile youtube site pauses video play when tab loses focus. Likely it does it through javascript code. The same behavior is for websites with an embedded video. The workaround would be to use desktop version of the site, but it is uncomfortable to use on phones. The difficult thing is that we cannot ignore 'pause' method, because we cannot say, does it come because tab is hidden or because user pressed the button.

**Comment by AlexeyBarabash** [comment] 2017-11-15 14:19
Made a new PR for this feature https://github.com/brave/browser-android-tabs/pull/462 .

Now video plays well for mobile youtube. 

There is an option in Settings => Site settings => Media  => Video in background to turn this feature on, default  value is 'disabled'.

For for sites with embedded mobile youtube videos this feature does not work, because video is nested inside of iframe and we have access to manage pause in easy way.

**Comment by AlexeyBarabash** [comment] 2017-11-16 19:33
Made a new PR and have now the beta build https://github.com/brave/browser-android-tabs/releases/tag/v1.0.38(beta2) .

**Comment by LaurenWags** [comment] 2017-11-16 22:19
### Test Plan (in progress)

Scenario 1 (update case/setting is off)
1. Update from previous version.
2. Navigate to Settings > Site Settings > Media > Video in background.
3. Verify setting is disabled.
4. Open YT video in tab, start video.
5. Open a new tab/switch to another tab, verify video does not play.
6. Go back to YT video tab, start video.
7. Background the app, verify video does not play.
8. Go back to YT video tab, start video.
9. Switch off the device display, verify video does not play.

Scenario 2 (update case/enable setting)
1. Update from previous version.
2. Navigate to Settings > Site Settings > Media > Video in background.
3. Enable setting. Verify you are prompted about relaunch. Choose to relaunch now.
4. Verify when relaunch occurs, your open tabs are preserved.
5. Open YT video in tab, start video.
6. Open a new tab/switch to another tab, verify video continues to play.
7. Background the app, verify video continues to play.
8. Switch off the device display, verify video continues to play.

Scenario 3 (clean install/enable setting)
1. Clean install of build.
2. Navigate to Settings > Site Settings > Media > Video in background.
3. Enable setting. Verify you are prompted about relaunch. Choose later.
4. Open a couple of tabs, one of them being a youtube video. 
5. Completely close Brave (not just background the app).
6. Reopen Brave.
7. Go to your YT video tab, start video.
8. Open a new tab/switch to another tab, verify video continues to play.
9. Background the app, verify video continues to play.
10. Switch off the device display, verify video continues to play.

**Comment by LaurenWags** [comment] 2017-11-16 22:38
@AlexeyBarabash - While testing this I noticed something odd.
(pre req - make sure your device has the screen locked via pin, etc)
1. Open YT video in normal tab, start playing video.
2. Turn off the display.
3. Turn on the display (I press the power button on my device)
4. Background image is now a still from the video you were playing, not your normal background. Like this: 
![screenshot_2017-11-16-17-09-19](https://user-images.githubusercontent.com/28145373/32919683-b1efe5c0-caf4-11e7-83b6-1a5f363a620b.png)
5. Open Brave back up.
6. Open an incognito tab and navigate to the same YT video, start video.
7. Turn off the display.
8. Turn on the display.
9. Device background does not display still from video, shows normal device background: 
![screenshot_2017-11-16-17-15-36](https://user-images.githubusercontent.com/28145373/32919755-e7b9f8bc-caf4-11e7-98c6-a13391c9cef4.png)

**Comment by AlexeyBarabash** [comment] 2017-11-22 11:19
I also was able to see this weird behavior of background image on the lock screen on my tablet Cube Talk 9x.

**Comment by AlexeyBarabash** [comment] 2017-11-23 15:40
I have found the situation with preview on lock screen and incognito mode is an expected behavior.

Here is a place where things happens:
https://github.com/brave/browser-android-tabs/blob/6840c24c766d77ce930f46bafa452d81d5b83a7d/chrome/android/java/src/org/chromium/chrome/browser/media/ui/MediaNotificationManager.java#L875
For the private tab the preview bitmap is not passed.
For normal tab the bitmap is passed and there is no possibility to adjust its size and position.

Tried with a minimal sample of android-UniversalMusicPlayer. The preview was stretched on the lock screen on emulators Android versions 4.4-7.0.
Different behavior may be caused by vendor firmware, as I have MIUI on Xiaomi phone and don't see the the fullscreen preview.

**Closed** 2017-12-12 17:07 UTC
Labels: feature request
