### ISSUE TITLE
Close all Tabs or Close a single lone tab causes Brave to close

### ISSUE THREAD

**Issue by miladmaz12** [brave/browser-android-tabs#1425] opened 2019-04-04 02:48 UTC
## Description 
Similar to #490 

## Steps to reproduce 

   1. Close a lone tab or all tabs
   2. Brave the app causes to close

## Expected result
Brave should stay open/in the home page for the user

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? N/A

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.0.89

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment] 2019-04-04 13:48
Closing as dupe of #490 . Please see https://github.com/brave/browser-android-tabs/issues/490#issuecomment-463486273 for workaround

**Closed by srirambv** 2019-04-04 13:48 UTC
