### ISSUE TITLE
Tapping on Brave Rewards system notification yields no action

### ISSUE THREAD

**Issue by btlechowski** [brave/browser-android-tabs#1446] opened 2019-04-09 02:10 UTC
## Steps to reproduce 

   1. clean install Brave
   2. Get Brave Rewards system notification
   3. Tap on that notification

## Actual result 
Nothing happens. Usually tapping on a notification yields an action.

![Screenshot_20190409-040304_Samsung Experience Home](https://user-images.githubusercontent.com/34715963/55768388-043c8e00-5a7d-11e9-8b56-55d39051c465.jpg)

In order to perform notification action, I need to expand it and press `Zacznij` (which translates to `Begin`), then `chrome://rewards` is opened in Brave
![Screenshot_20190409-040626_Samsung Experience Home](https://user-images.githubusercontent.com/34715963/55768391-07d01500-5a7d-11e9-9a9a-5c0a0bd41583.jpg)

## Expected result
`chrome://rewards` is opened in Brave on tap

## Issue reproduces how often 
Easily reproduced

## Device details
   - Install type (ARM, x86):ARM
   - Device (Phone, Tablet, Phablet): Samsung s7
   - Android version: 8.0.0
   
## Brave version
Reproduced on Samsung s7, Android 8.0.0, BraveMonoarm v1.0.90-rc.2

cc @brave/legacy_qa @samartnik @SergeyZhukovsky

**Comment by LaurenWags** [comment] 2019-04-09 12:49
cc @anthonypkeane

**Comment by btlechowski** [comment] 2019-04-09 21:18
Not reproducible on Samsung s7, Android 8.0.0, BraveMonoarm v1.0.90-rc.3

**Comment by srirambv** [comment] 2019-04-10 14:41
Closing based on https://github.com/brave/browser-android-tabs/issues/1446#issuecomment-481444179. Looks to be fixed in rc3 and rc4 as well

**Closed by srirambv** 2019-04-10 14:41 UTC
Labels: QA/Test-plan-specified, QA/Yes, bug/BR

**Comment by kjozwiak** [comment] 2019-04-11 17:57
@srirambv should this be rechecked on the other remaining devices?

**Comment by srirambv** [comment] 2019-04-11 18:08
Not needed as its working on rc3 and rc4. Is it not working on your device?

**Comment by kjozwiak** [comment] 2019-04-11 18:16
Should probably be labelled as verified as the issue is labelled as `QA/Yes`. Going through the list of closed issues, this looks like it was missed and wasn't checked unless you click on the issue and read through the comments.

* Verification **PASSED** using `1.0.90 CR: 73.0.3683.90` on `Pixel 2 running Android 9`
