### ISSUE TITLE
Pull to refresh not working

### ISSUE THREAD

**Issue by jamesmudgett** [brave/browser-android-tabs#1349] opened 2019-03-16 03:48 UTC
User reported: Pull to refresh not working in 1.0.88 release. Needs more investigation. Origin https://twitter.com/sil/status/1106691539315642368

**Comment by stuartlangridge** [comment] 2019-03-16 17:08
Interestingly, it's only not working on one specific site: D&D Beyond. See https://www.dndbeyond.com/characters/6518445/UjSVOw for an example of a not-working page. I can confirm that pull to refresh worked on that site before the Android Brave change to place the toolbar at the bottom of the window.

**Comment by HennyBro** [comment] 2019-03-21 19:42
For me it's always working on my Pixel XL running Android Q Beta 1 and the latest 1.088 build.

**Comment by deeppandya** [comment] 2019-09-24 21:47
@anthonypkeane @SergeyZhukovsky I verified this issue with different websites. and it seems not work with only **https://www.dndbeyond.com/characters/6518445/UjSVOw**. it seems to be a bug in chromium as it behaves the same in chrome.

**Comment by SergeyZhukovsky** [comment] 2019-09-24 22:02
@deeppandya let's leave it for now, probably we will catch up the fix from uplift.

**Comment by anthonypkeane** [comment] 2019-09-25 18:28
Closing as bug from chrome

**Closed by anthonypkeane** 2019-09-25 18:28 UTC
Labels: QA/Yes, bug/BR, needs-investigation

**Comment by kjozwiak** [comment] 2019-11-05 06:57
Labelling this as `QA/No` as nothing was fixed. Quickly checked https://www.dndbeyond.com/characters/6518445/UjSVOw and I can still reproduce issue on both `Brave` & `Chrome`:

* `Brave 1.5.0 CR: 78.0.3904.90` using `Pixel 2 XL Android 10` - Reproduced
* `Chrome 78.0.3904.62` using `Pixel 2 XL Android 10` - Reproduced
