### ISSUE TITLE
'Close all Tabs' causes Brave to Close

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#490] opened 2017-12-15 22:04 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
On some Android versions when you 'Close all Tabs', Brave closes as well. 

**Device Details:**
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Phone
   - Android Version: 7.0
    
**Brave Version:**
1.0.39

**Steps to reproduce:**
    1. Open a few tabs
    2. Tap on the tab count
    3. Tap on the 3 dots menu
    4. Tap on 'Close all tabs'

**Actual Behavior**
On some Android OS versions (like 7.0) the tabs close and then Brave closes. On other OS versions (like 5.1), only the tabs close and Brave remains open. 

**Expected Behavior**
Only tabs should close, Brave should remain open.

**Is this an issue with Beta build?**
n/a

**Is this an issue in the currently released version?**
yes

**Can this issue be consistently reproduced?**
yes

**Extra QA steps:**
    1. 
    2. 
    3.

**Website problems only:**
  - did you check with Brave Shields down?
  - did you check in Chrome for same behavior? Yes - chrome has the same behavior on both operating systems

**Screenshot if needed:**

**Any related issues:**

**Comment by jonathansampson** [comment] 2019-02-13 23:42
This issue recently surfaced again. If you close all tabs in 1.0.77, the app itself will close.

**Comment by Brave-Matt** [comment] 2019-02-13 23:52
Going further, all tabs can be close by any method as well. Meaning that it's not restricted to the `Close all tabs` option. If you only have one tab open in tab view and you swipe or 'x' out of it, this also forces Brave to close. Just in case there was any confusion.

I've got about 1000 +1's on Zendesk from Android users requesting this behavior either be reverted or to add option for either (I like this solution personally).

**Comment by kjozwiak** [comment] 2019-02-14 00:23
Reproduced this several times which is a bit annoying. @SergeyZhukovsky @srirambv should we get this into `1.0.80` as we're getting a decent amount of complaints from the community?

**Comment by Brave-Matt** [comment] 2019-02-14 00:36
Just a handful for emphasis:
![image](https://user-images.githubusercontent.com/3299098/52753810-04546c00-2fad-11e9-904a-e04b7f31e89e.png)
![image](https://user-images.githubusercontent.com/3299098/52753839-2817b200-2fad-11e9-8988-861f5e890b44.png)
(☝️ translated)
![image](https://user-images.githubusercontent.com/3299098/52753862-3cf44580-2fad-11e9-9788-de9d1bd4a26c.png)

**Comment by SergeyZhukovsky** [comment] 2019-02-14 01:42
Turning off Home Page option in Settings prevents from closing the browser when close all tabs.

**Comment by kjozwiak** [comment] 2019-02-14 02:11
I guess there's at least a work around, but we should fix this sooner than later as we're getting tons of complaints which is also affecting our reviews on GPS as @Brave-Matt demonstrated above.

**Comment by kjozwiak** [comment] 2019-02-14 03:12
> Turning off Home Page option in Settings prevents from closing the browser when close all tabs.

Quickly talked to @SergeyZhukovsky. Seems like Chrome doesn't have the `Home Page` setting under their `Basic` settings. As @SergeyZhukovsky mentioned above, disabling the `Home Page` options fixes the above. We'll need to investigate to figure out why we're showing the setting and Chrome isn't which will require some work. Will get fixed on the next release 👍

**Comment by thanuj10** [comment] 2019-02-14 03:17
Or just make chrome://newtab as the default homepage and see. Brave will not close when all tabs are closed.
iirc, Brave already had chrome://newtab as the dafault homepage, but changed to google.com in the recent builds.

**Comment by Brave-Matt** [comment] 2019-02-14 03:57
@kjozwiak @SergeyZhukovsky, note that many users are still affected by #766 so even this workaround wouldn't help because they're unable to access the Homepage button/setting.

**Comment by srirambv** [comment] 2019-02-14 04:27
@kjozwiak @SergeyZhukovsky I suggest we disable Home button by default. I don't think the feature is being used widely (may be @Brave-Matt could confirm via support tickets if its being reported) and it just uses unnecessary space on the URL bar.

>Brave already had chrome://newtab as the dafault homepage, but changed to google.com in the recent builds.

This is a problem on Samsung devices. It sets Google as home page by default with their own query parameters on any browser that runs on the device.

**Comment by srirambv** [comment] 2019-02-14 04:27
Moving the issue to 1.0.81.

**Comment by kjozwiak** [comment] 2019-02-14 04:30
> This is a problem on Samsung devices. It sets Google as home page by default with their own query parameters on any browser that runs on the device.

Yup, definitely not seeing it on any of my Pixel devices.

**Comment by Brave-Matt** [comment] 2019-02-14 04:30
@srirambv, can confirm user want home button option _available_, not necessarily by default. But option to enable it for sure.

**Comment by srirambv** [comment] 2019-02-14 04:35
For now could you please respond to the queries to disable Home button. We can have this fixed with showing home button and push it in 1.0.81

**Comment by AlexeyBarabash** [comment] 2019-02-14 11:29
I have Samsung phone (Android 8.0.0), but don't see the issue.

**Comment by EyanGoldman** [comment] 2019-07-18 21:08
Closing as this ticket will be fixed with #1716

**Closed by EyanGoldman** 2019-07-18 21:08 UTC
Labels: QA/Test-plan-specified, QA/Yes, bug, release-notes/include
