### ISSUE TITLE
Implement Virtual Grants

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#2430] opened 2020-01-08 19:43 UTC
## Description 

Implement Virtual Grants on Android Tabs

**Comment by samartnik** [comment] 2020-01-11 13:09
@anthonypkeane what should be done here? Is it duplicate of https://github.com/brave/browser-android-tabs/issues/2420

**Comment by samartnik** [comment] 2020-01-11 19:20
Closing as duplicate. @anthonypkeane let me know if it's not. We will re-open it.

**Closed by samartnik** 2020-01-11 19:20 UTC
Labels: QA/Yes, closed/duplicate
