### ISSUE TITLE
Unable to authenticate into Amazon or view certain pages on mobile

### ISSUE THREAD

**Issue by Brave-Matt** [brave/browser-android-tabs#1077] opened 2019-02-05 00:16 UTC
## Description 
Logging into Amazon using standard login function works fine. However, once logged in, if you attempt to view certain screens - "Orders" is an easy to produce one - you'll be asked to authenticate again. After doing so, instead of being directed to the page in question, you remain on the Amazon auth page as if you'd just arrived there.

## Steps to Reproduce 

   1. Visit and login to Amazon.com
   2. Open the Amazon sidebar menu and select `Orders`
   3. Attempt to authenticate after clicking

## Actual result: 
You remain on the Amazon authentication page

## Expected result:
Should be redirected to "Orders" page

## Issue reproduces how often: 
Always

## Issue happens on: 
   - Current Playstore version? Yes
   
## Brave version:
1.7.2, 1.7.6

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? No

### Additional Information

User reports:
https://community.brave.com/t/amazon-not-allowing-2-factor-login-from-brave-mobile-browser/43982
https://community.brave.com/t/cant-log-into-amazon/44031/5

**Comment by samartnik** [comment] 2019-02-08 20:52
Seems to be fixed in 1.0.79

**Closed by samartnik** 2019-02-08 20:52 UTC

**Comment by srirambv** [comment] 2019-02-11 11:46
Verification passed Android ARM. Followed the steps from original issue description.

**Comment by kjozwiak** [comment] 2019-02-12 04:41
@samartnik just curious, what was the original issue? Was this Brave related or something that we got upstream from the CR bump and was fixed after another minor CR72 bump?

**Comment by samartnik** [comment] 2019-02-12 13:30
@kjozwiak I'm not sure. It just hasn't reproduced with new build. We didn't research it deeply.
