### ISSUE TITLE
New tab button creates 2 tabs 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#2295] opened 2019-11-14 14:03 UTC
## Description 
New tab button creates 2 tabs 

## Steps to reproduce 

   1. Close all tabs from tab tray
   2. Tap on new tab
   3. Creates 2 new tabs

## Actual result 
New tab button creates 2 tabs 

## Expected result
Should only create 1 tab

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build?

## Device details
   - Install type (ARM, x86): All
   - Device (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.5.0

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

Original report: https://community.brave.com/t/problem-after-close-all-taps/92269/2

**Comment by szaimen** [comment] 2019-11-15 03:02
Worse in my opinion than this behavior is, that when I instantly click on the "create new tab" button after closing all tabs, I have to wait until the "do you want to reopen all closed tabs" is gone after a few seconds. Which I do really often and is very disturbing.

**Comment by srirambv** [comment] 2019-11-15 15:15
@szaimen this was discussed [here](https://github.com/brave/browser-android-tabs/issues/2031#issuecomment-539572610). I will open a new issue for improving the timing and behaviour.

**Comment by i6jm** [comment] 2019-11-15 16:21
Update 1.5.1 was just released and the problem is not resolved

**Comment by kjozwiak** [comment] 2019-11-22 03:52
+1 from a user who gave a one star rating/review via the GPS due to this issue as well.

**Comment by i6jm** [comment] 2019-11-23 06:18
Version 1.5.2 has just been released and the problem is not resolved

**Comment by srirambv** [comment] 2019-11-23 12:55
@i6jm as you can see the issue is still open meaning its not fixed. Its currently marked for 1.6.0 release

**Comment by srirambv** [comment] 2019-11-28 12:12
+1 from https://community.brave.com/t/when-you-closing-all-tabs-then-tap-on-symbol-why-brave-opens-double-tabs-at-once/95388/2

**Closed** 2019-11-28 13:41 UTC
Labels: QA/Yes, bug, regression, release-notes/include

**Comment by btlechowski** [comment] 2019-11-28 21:22
Verification passed on BraveModernarm v1.6.0-rc.1 on Huawei MediaPad M3 Lite 10 (Android 7.0). 
Verified the test plan from the description. One tab was opened.

**Comment by i6jm** [comment] 2019-12-06 22:03
it fix thank you
