### ISSUE TITLE
sync - Desktop bookmarks do not show up on mobile and vice-versa

### ISSUE THREAD

**Issue by mithodin** [brave/browser-android-tabs#1076] opened 2019-02-04 10:58 UTC
## Description
I have multiple desktop instances in a sync chain. When I add a mobile device (release 1.0.77) to the sync chain, no desktop bookmarks ever show up on the mobile device and no mobile bookmarks show up on the desktop devices

## Steps to Reproduce
   1.  Create a sync chain on desktop, add a few bookmarks
   2. Add mobile device to the sync chain
   3. Check bookmarks on mobile device
   4. Check bookmarks on desktop device

## Actual result:
No desktop bookmarks can be seen on mobile.
No mobile bookmarks can be seen on desktop.

## Expected result:
Bookmarks actually propagate from desktop to mobile and vice-versa.

## Issue reproduces how often:
Happens every time.

## Issue happens on:
   - 1.0.77

## Device Details:
   - Install Type(ARM, x86): Modern ARM
   - Device(Phone, Tablet, Phablet): Phone
   - Android Version: 8.1.0
   
## Brave version:
   - 1.0.77 (mobile), 0.59.34 (desktop)

**Comment by srirambv** [comment] 2019-02-04 11:39
Following the steps from issue I can't reproduce the issue. Bookmarks from desktop sync to Mobile but bookmarks from Android doesnt propagate to desktop which should be fixed as part of brave/sync#277. When Android device is sync'd there is a delay in getting bookmarks. It took me about 5 mins post joining sync chain for the mobile to receive bookmarks. Adding a second Android device syncs bookmarks instantly. 

@mithodin Does any of the device in the sync chain had sync reset before and then rejoined?

**Comment by mithodin** [comment] 2019-02-04 12:13
It is definitely not a time issue, since I've waited a few hours for the bookmarks to show up and there is nothing.
I had tried to sync the android device once before with an earlier build, I can't remember which one, though. I removed it from the sync chain then.

**Comment by srirambv** [comment] 2019-02-04 12:15
Just a note adding a new bookmark on desktop propagates to Android devices. Existing ones don't propagate from Android-Desktop. Might be related to #1063 as well

**Comment by SergeyZhukovsky** [comment] 2019-02-04 14:48
@mithodin just to clarify. Do you see bookmarks on Android device if you create them on desktops? I'm confused as in the original description you said you don't, but at the latter message you said you do.

**Comment by mithodin** [comment] 2019-02-04 14:49
I do not see any bookmarks that were created before the device joined the sync chain. If I create new bookmarks, those seem to show up after a while.

**Comment by PunnyBoi** [comment] 2019-02-05 15:39
So is there no way I can migrate existing bookmarks to other synced devices?

**Comment by srirambv** [comment] 2019-02-05 15:50
This issue is fixed and should be available in the next update for both desktop and Android.

**Closed by srirambv** 2019-02-05 15:50 UTC
Labels: QA/Yes, bug, feature/sync
