### ISSUE TITLE
Closing "Add funds" dialog  still leaves a user at `chrome://rewards/#add-funds` page. 

### ISSUE THREAD

**Issue by gdregalo** [brave/browser-android-tabs#1043] opened 2019-01-25 02:05 UTC
Closing `Add funds` dialog  still leaves a user at `chrome://rewards/#add-funds` page.  Which is not correct. The user is supposed to find herself at Settings `chrome://rewards` url instead. 
We are trying not to keep opened several `settings ` (at `chrome://rewards`) and `Add funds` (chrome://rewards/#add-funds) pages simultaneously. The above issue makes it difficult to find `who is who` here.

## Steps to Reproduce 

   1. 
   2. 
   3. 

## Issue happens on: 
   - Current Playstore version?
   - Beta build?

## Device Details:
   - Install Type(ARM, x86):
   - Device(Phone, Tablet, Phablet):
   - Android Version:
   
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by ryanml** [comment] 2019-01-25 02:12
Duplicate of: https://github.com/brave/browser-android-tabs/issues/1001

**Closed by ryanml** 2019-01-25 02:12 UTC
Labels: bug/BR
