### ISSUE TITLE
Sample ad notification isn't launching Brave 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1805] opened 2019-07-03 16:13 UTC
## Description 
Sample ad notification isn't launching Brave 

## Steps to reproduce 

   1. Install play store build, do not enable rewards
   2. Install 1.1.0-6 ads build
   3. Enable rewards from in-app notification
   4. Wait for sample ad notification to show up
   5. Quit browser and tap on the sample ad notification

## Actual result 
Ad notification is dismissed but Brave is never launched to open the landing page for the sample ad

## Expected result
Should launch Brave irrespective of which browser is set as default and load the landing page

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? N/A
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone (Huawei P20)
   - Android version: 8.1.0
   
## Brave version
1.1.0-6 x64 ads build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment] 2019-07-03 16:40
step7: After I tap on the sample ad notification, I am getting the below message:

![image](https://user-images.githubusercontent.com/38657976/60609417-40af2a00-9ddf-11e9-963a-a117720cd995.png)


Device and build details:

- Samsung Galaxy J3 version 5.1.1
- Build - BraveModernarm `v1.1.0-brave-ads-6`

**Comment by anthonypkeane** [comment] 2019-07-03 16:50
The bug is step 7 seems to be unrelated and should be looked into

**Comment by LaurenWags** [comment] 2019-07-03 19:56
Logged https://github.com/brave/browser-android-tabs/issues/1811 for https://github.com/brave/browser-android-tabs/issues/1805#issuecomment-508168765

**Comment by tmancey** [comment] 2019-07-05 23:01
Closing as a duplicate of #1811

**Closed** 2019-07-05 23:23 UTC
Labels: QA/Yes, bug

**Comment by GeetaSarvadnya** [comment] 2019-07-08 10:53
- Verification passed on Samsung Galaxy J3 version 5.1.1 running Bravemodernarm `1.1.0-brave-ads-8` build
