### ISSUE TITLE
"Chromium" text is found instead of "Brave" in storage access pop up

### ISSUE THREAD

**Issue by prasanthp96** [brave/browser-android-tabs#506] opened 2018-01-04 11:16 UTC
**Did you search for similar issues before submitting this one?**
yes

**Description:**
"Chromium" text was found in the storage access pop up on the brave browser instead of "Brave" 

**Device Details:**
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Motorola Moto G3
   - Android Version: 7.1.2
    
**Brave Version:**
1.0.40

**Steps to reproduce:**
    1.Make a fresh install of Brave browser
    2. Go to this page https://i.gadgets360cdn.com/large/apple_1_reuters_1509683067613.jpg
    3. Long tap the image and tap on "Download image" in menu

**Actual Behavior**
A pop up containing a text "Chromium needs storage access to files " is shown

**Expected Behavior**
Text must be "Brave needs storage access to files "

**Is this an issue with Beta build?**
Not yet checked

**Is this an issue in the currently released version?**
yes

**Can this issue be consistently reproduced?**
yes

**Extra QA steps:**
    1. 
    2. 
    3.

**Website problems only:**
  - did you check with Brave Shields down?
  - did you check in Chrome for same behavior?

**Screenshot if needed:**
![screenshot_20171228-004027](https://user-images.githubusercontent.com/11797131/34581888-1c628d1a-f1b8-11e7-9f03-e68bf7fab81a.png)

**Any related issues:**

**Comment by AlexeyBarabash** [comment] 2018-01-05 07:50
Duplicate of https://github.com/brave/browser-android-tabs/issues/502

**Closed by AlexeyBarabash** 2018-01-05 07:50 UTC
Labels: QA/steps-specified, release-notes/include

**Comment by LaurenWags** [comment] 2018-01-31 17:37
Checked with https://github.com/brave/browser-android-tabs/issues/502
