### ISSUE TITLE
Monthly payment not reflected

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-android-tabs#1141] opened 2019-02-19 08:21 UTC
Go to ac settings and try to select monthly payment. You can select it but amount is always 10 BAT. If you close ac settings you can see that monthly was saved. So I think problem is with UI not displaying correct amount.

![screenshot_20190219-092050](https://user-images.githubusercontent.com/9574457/53000049-b4036100-3427-11e9-9000-2926efec5599.png)

**Comment by ryanml** [comment] 2019-02-21 09:50
Fixed via: https://github.com/brave/browser-android-tabs/commit/0ed43295738dda5643594cb1f4cdefe468177c5b

**Closed by ryanml** 2019-02-21 09:50 UTC
Labels: QA/Yes, bug/BR, priority/P1

**Comment by GeetaSarvadnya** [comment] 2019-02-28 19:45
The issue is still reproducible on 1.0.83

**Comment by LaurenWags** [comment] 2019-03-06 21:14
Issue reproduces with 1.0.85 also.
