### ISSUE TITLE
Sync gets stuck in Loading devices page 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#924] opened 2018-12-11 07:45 UTC
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
Sync gets stuck in Loading devices page 

## Devices
Device 1: `0.58.11` (sync chain creator)
Device 2: Samsung Tab running `1.0.71(sync1)`
    
**Steps to reproduce:**
    1. Create Sync chain on bc
    2. Import a bookmark HTML file
    3. Add bookmarks on Android device
    4. Enable Sync on Android by entering code words
    5. Reset sync on bc and close the browser
    6. Android gets stuck in `Loading devices` page and never comes out of it. Back button doesn't work so only option is to remove app from memory and relaunch to use it. Tapping twice on back button shows this not responding message
![screenshot_20181211-024238_brave](https://user-images.githubusercontent.com/17010094/49785443-968a8a80-fd46-11e8-8de3-35f0c7748297.jpg)

**Actual Behavior**
Sync gets stuck in Loading devices page 

**Expected Behavior**
Not sure what the expected behaviour is. I assume it should either error out or join the sync chain

**Is this an issue with Beta build?**
Yes

**Is this an issue in the currently released version?**
N/A

**Can this issue be consistently reproduced?**
Yes

**Any related issues:**
cc: @darkdh @brave/android @brave/legacy_qa

**Comment by LaurenWags** [comment] 2018-12-12 17:16
Reproduced today with device1 = macOS using build below and device2=Android.

Interestingly enough, if I click Close App, Brave doesn't close, but it does close the Sync page and takes me back to my open tab. Also, this is what's happening on the mac laptop, the Android device is getting listed multiple times:
![screen shot 2018-12-12 at 12 14 11 pm](https://user-images.githubusercontent.com/28145373/49886461-af0ea980-fe07-11e8-84bb-e4805d4ca40f.png)

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta(64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

**Comment by AlexeyBarabash** [comment] 2018-12-17 11:22
Particularly fixed by  https://github.com/brave/browser-android-tabs/pull/934 , Android does not hung, but brave-core is still in devices list on Android.

**Comment by AlexeyBarabash** [comment] 2018-12-19 11:15
The part of the issue is fixed by @darkdh  in  https://github.com/brave/brave-core/pull/1135 .

**Closed** 2018-12-21 11:35 UTC
Labels: bug, feature/sync, priority/P2, release/blocking

**Comment by LaurenWags** [comment] 2019-01-04 22:03
Verified passed with 1.0.72 (sync1)

**Comment by btlechowski** [comment] 2019-01-30 22:56
Verification passed on Samsung s7 (ARM), Brave 1.0.75.

Initial sync of Android device and desktop(sync chain creator) took 7 seconds.
