### ISSUE TITLE
Implement *Brave* user-agent

### ISSUE THREAD

**Issue by tomlowenthal** [brave/browser-android-tabs#712] opened 2018-08-15 22:49 UTC
Exciting news: we have enough users on Android that it probably makes sense to use a ~~*Brave*~~ user-agent string! Unlike the temporary fix in #130, we no longer need to fake details (Android version, device, build…) that we don't want to disclose.

Here's the new template:
`````
Mozilla/5.0 (Linux; Android) like AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.111 Mobile Safari/537.36 Brave
`````

Those Webkit, Chrome, and Safari versions need to stay current — they should match the equivalent Chrome versions. We won't be presenting a Brave version number because we think that feature-detection should be based on actually detecting features, not divination based on tables of version strings.

**Comment by tomlowenthal** [comment] 2018-08-22 20:36
Exciting UA updates. After a most detailed discussion, a small change to pin an Android version number and reduce webcompat issues.
Mozilla/5.0 (Linux; Android 8.1.0) like AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.111 Mobile Safari/537.36 Brave

**Comment by DI555** [comment] 2018-08-23 10:43
Why Brave has a hardcoded 'command line' ???
I saw here an issue about 'command line arguments in a file' !!!
Write to it, dev team), any ua what you would like !
If you affraid that users will editingi it, put this file optionally to system app folder(no access without root rights).
Imo this is the best way, what do you think?

**Comment by sviluppoSoftware** [comment] 2019-02-26 12:11
Hi, unfortunately despite the recent update for android (version 1.0.82) the user agent "protection" still does not work, ie through this test https://browserleaks.com/ip are still shown the model of the phone and the browser version ( 72.0 etc. ....)

**Comment by binarious** [comment] 2019-03-21 10:56
@tomlowenthal @samartnik I can confirm that the latest version still includes the phone model in the user agent. Is this intended? Can we disable it? Shall I open up another issue?

**Comment by bbondy** [comment] 2019-05-13 18:16
For now all we want to do is append Brave and a space before Brave please @samartnik

**Comment by medmr1** [comment] 2019-07-25 21:08
This is a big disappointment. If you aren't going to include a really basic privacy feature in your browser like user agents that don't leak the phone model, you need to change all your marketing so its not misleading people into thinking this browser is privacy focused. Maybe this is perpetually in the backlog because Google won't approve a browser that is actually privacy focused on Android?

**Comment by waldebart** [comment] 2019-08-23 13:46
Please remove phone model from the user agent string.

**Comment by nexx512** [comment] 2019-10-18 19:17
As I have don't have a mainstream phone, the user agent is currently one of the most significant feature to identify my uniqueness because of the phone model. Unfortunately I do have to switch browsers now until this is fixed. I just found out about the leak today. It is very sad to see that a privacy focused browser has such a basic and huge privacy leak.

**Comment by tjm00** [comment] 2019-11-02 07:33
The user agent is now ridiculously revealing. At the least it should reveal less information with fingerprinting protection on.

**Comment by tobia** [comment] 2019-11-03 16:58
Can we *omit* the User Agent entirely, when one opts-in to the existing "Fingerprint protection" setting?

I, as well as other people who go out of their way to enable that setting by default, have no interest in websites that fail to work unless one pretends to be Mozilla, AppleWebKit, KHTML, Gecko, Chrome, or Mobile Safari (see list of keywords in OP.)

This is not the browser wars of the 90s anymore. Whoever serves different HTML depending on that clusterf*** of keywords deserves to have their tab closed and my eyeballs/money/clicks go somewhere else.

**Comment by stealthcopter** [comment] 2019-11-19 19:17
I would be happy to submit a pull request with the changes necessary for this but I think it'd be good to decide how the `User-Agent` should be sent when "Fingerprint protection" is enabled. 

@tobia My concern with your solution of sending no User-Agent is that in itself may be somewhat of a unique identifier, as I doubt many browsers send nothing through. So perhaps it would be best to pick one of the most popular current User-Agents instead? Thoughts.

**Comment by tjm00** [comment] 2019-11-21 06:58
Why not just a vanilla Chrome one? Among the most common ones out there, I suspect, and websites serving different pages based on it are unlikely to break.

**Comment by drokath** [comment] 2019-11-24 17:48
This issue is linked with #2171

**Comment by RandomErrorMessage** [comment] 2019-11-25 23:53
This isn't a complicated issue. User agents are virtually never beneficial for the end-user. They're used by website operators to target users with anti-features and advertisements. The obvious conclusion is that it's **never helpful** for Brave to identify itself as Brave.

The Brave browser should actively lie by default, pretend to be Chrome. There should be a list of other popular user-agents to impersonate. Custom user-agent. All of these options are better than advertising your usage of Brave.

**Comment by tomlowenthal** [comment] 2019-12-05 00:12
To be clear, the "vanilla" Chrome UA is what's currently sent. But the Chrome UA contains a lot of details we'd like to exclude. Fixing them (for instance: pretending that Brave is always running on one specific phone) will probably create some compatibility problems. Just plain removing them will make Brave stand out as different from Chrome — because a real Chrome would have included that info. So if we're going to cut that info out, we might as well add "Brave".

**Comment by nexx512** [comment] 2019-12-07 06:49
Then why not let the user decide if he wants to fake the phone model string in the UA and live with incompatibilities?

**Comment by waldebart** [comment] 2019-12-07 21:38
Since there's no difference between Chrome and Brave UA it is not so easy to speak about "privacy protection". These UA spill definitely to much info about the system. Chrome's one is made in sake of user tracking. On the other hand, Firefox, Kiwi, Priwacy Browser and DuckDuckGo are able to hide part of such info and do perform well in daily use.
Pity, I won't use Brave on my mobile devices untill it got changed :(

**Comment by avoidik** [comment] 2019-12-11 10:31
I'm switching off to a different browser with option to change UA until this feature

**Comment by anthonypkeane** [comment] 2019-12-19 21:20
Closing as this will be a company wide project.

**Closed by anthonypkeane** 2019-12-19 21:20 UTC
Labels: QA/Yes, feature/privacy
