### ISSUE TITLE
Bookmarks added on Android when offline are not shown in proper folder structures on ios

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#799] opened 2018-10-25 13:31 UTC
**Did you search for similar issues before submitting this one?**

**Description:**
Bookmarks added on Android when offline are not shown in proper folder structures on ios

**Device Details:**
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): iPhone -IOS12
   - Android Version: Android 5.1.1
    
**Brave Version:**
Sync Build

**Steps to reproduce:**
    1. Sync iOS and Android through QR code
    2. Start creating BM's in Android
    3. Bookmark any site outside the folder
    4. Bookmark any site, click on Edit and move the site to Folder A
    5. Verify the BM's and folder structure in ios
    6. Disconnect Android device from network/offline
    7. Bookmark any site in Folder B, which is created inside the folder A
    8. Re-connect Android network
    9. Verify the BM's and folder structure in ios 
   10. Disconnect ios device from network/offline
   11. Bookmark any site in Folder C, which is created inside the folder B
   12. Re-connect IOS network
   13. Verify the BM's and folder structure in ios

**Actual Behavior**
Bookmarks added in the 3rd level hierarchy (Folder c) are not getting imported in Ios

**Expected Behavior**
Bookmarks added in the 3rd level hierarchy (Folder c) should also not get imported in Ios as Folder B bookmarks imported

**Comment by srirambv** [comment] 2018-10-25 13:35
Probably dupe of #790

**Closed** 2018-10-25 13:40 UTC
Labels: bug, duplicate, feature/sync
