### ISSUE TITLE
Youtube full screen mode hide top and bottom area

### ISSUE THREAD

**Issue by chkk525** [brave/browser-android-tabs#2298] opened 2019-11-15 07:34 UTC
## Steps to reproduce 

   1. 
   2. 
   3. 

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment] 2019-11-15 16:09
closing as dupe of #2299 as it has more details

**Closed by srirambv** 2019-11-15 16:09 UTC
