### ISSUE TITLE
Name-less Bookmarks Don't Sync

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-android-tabs#1158] opened 2019-02-19 17:16 UTC
## Description
[A user on Twitter](https://twitter.com/mrbilltran/status/1097717382909284352) has found that bookmark items lacking a name will not sync to Android from Desktop. Temporarily adding a name to these items resulted in them syncing as expected.

## Steps to Reproduce 
1. Bookmark an item on desktop, and edit to remove the text name.
2. Sync devices.

## Actual result:
Items without names don't sync.

## Expected result:
Items without names should sync.

## Issue reproduces how often:
Easily reproduced.

## Issue happens on:
   - Current Playstore version? Yes
   - Beta build? TBD

## Device Details:
   - Install Type(ARM, x86): TBD
   - Device(Phone, Tablet, Phablet): TBD
   - Android Version: TBD
   
## Brave version:
TBD

**Comment by srirambv** [comment] 2019-02-19 17:22
Dupe of #1083

**Closed by srirambv** 2019-02-19 17:22 UTC
