### ISSUE TITLE
Twitter (lite) not loading with ad-blocker

### ISSUE THREAD

**Issue by silentBoY-hu** [brave/browser-android-tabs#1921] opened 2019-08-05 12:41 UTC
## Description 
I have an issue with the ad-blocker in Twitter. If this turned on Twitter did'nt show any posts anywhere, but it is turned off this website absolutely working just fine. Here is the video of the issue. 

## Steps to reproduce 

   1. Turned off ad-blocker
   2. 
   3. 

## Actual result 
Not showing any or every posts on Twitter (Lite)
![Screenshot_2019-08-05-14-38-12](https://user-images.githubusercontent.com/53769481/62465235-b61b6b00-b78e-11e9-938c-fa71a2ee86c2.png)
![Screenshot_2019-08-05-14-38-12](https://user-images.githubusercontent.com/53769481/62465286-cf241c00-b78e-11e9-864c-389b6c2379bf.png)
![Screenshot_2019-08-05-14-37-55](https://user-images.githubusercontent.com/53769481/62465296-d5b29380-b78e-11e9-8132-0957b39082c7.png)
![Screenshot_2019-08-05-14-37-36](https://user-images.githubusercontent.com/53769481/62465310-dea36500-b78e-11e9-9086-dcc00c19e16d.png)
![Screenshot_2019-08-05-14-37-31](https://user-images.githubusercontent.com/53769481/62465341-ed8a1780-b78e-11e9-8cdf-d3ce2b58b293.png)
Video about the issue: https://youtu.be/l-Doha7djrI

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes (1.2.0 Beta 1)

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Huawei P8 Lite (ALE-L21)
   - Android version: 6.0 Marshmallow
   
## Brave version
1.2.0 BETA 1

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by srirambv** [comment] 2019-08-05 13:03
Dupe of #1907.

**Closed by srirambv** 2019-08-05 13:03 UTC
