### ISSUE TITLE
Brave stats not good readable with some ntp images

### ISSUE THREAD

**Issue by szaimen** [brave/browser-android-tabs#2324] opened 2019-11-28 20:23 UTC
## Description
Brave stats not good readable with some ntp images

## Steps to reproduce

   1. Install brave 1.6.0
   2. Open new tab
   3. Some stats not good readable

## Actual result 
Stats are not good readable

## Expected result
Stats should be visible

## Issue reproduces how often 
Easily reproduced

## Brave version
1.6.0

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? No

### Additional information
![Screenshot_20191128-211547_Brave](https://user-images.githubusercontent.com/42591237/69830494-56593c00-1225-11ea-85de-cd63dfc63267.jpg)
![Screenshot_20191128-211553_Brave](https://user-images.githubusercontent.com/42591237/69830495-56593c00-1225-11ea-8106-48b144793b6d.jpg)
![Screenshot_20191128-211609_Brave](https://user-images.githubusercontent.com/42591237/69830496-56593c00-1225-11ea-8c7c-6751d2d3e699.jpg)
![Screenshot_20191128-211619_Brave](https://user-images.githubusercontent.com/42591237/69830497-56593c00-1225-11ea-8a5d-4e5df4e27051.jpg)

**Comment by srirambv** [comment] 2019-11-28 21:36
Closing as dupe of #2325

**Closed by srirambv** 2019-11-28 21:36 UTC
