### ISSUE TITLE
[Important] Terrible User Agent making Brave completely non-private and trivial to fingerprint 

### ISSUE THREAD

**Issue by MegaArthur** [brave/browser-android-tabs#582] opened 2018-03-25 20:37 UTC
### IMPORTANT

(I know there's an issue similar to that, but the devs seem to be not paying attention (issue 1 year old, no response from devs) so I guessed I'd revive this here, with more info and suggestions.)

So, I guess Brave is supposed to be a _private_ browser for Android, huh? 

Well, good luck with that everybody if the user agent makes it so effing unique, all with the android version and phone model, that disabling JS won't do shit.

I really do not get why this hasn't been brought to the devs' attention/the devs haven't thought about it, but it's such a major privacy flaw, making Brave literally one of the least private browsers, while nobody seems to care.

Why not make it so that either:
- The user can choose from one of the predefined user agent strings, eg. the one that Tor Browser uses or Firefox with resist.fingerprinting on?

This adresses the devs' "concern" that the users wouldn't update their strings to match the new versions

Or

- The user agent isn't just **full of unique fingerprinting information which (I guess) can be removed just as easily as someone has added it, for no concievable reason, maybe only to decrease privacy.**

 I mean, really, who thought about including the device model and some system info in the user agent string, when pretty much no other does that?

Until then, everybody should treat Brave for android as _non-private_, no matter if someone turns off JS and turns on FP protection.

**Comment by D0ve** [comment] 2018-03-26 22:59
There must be the switch in command line to define custom user agent. I dunno, is it possible using command line switch in app on android?

**Comment by MegaArthur** [comment] 2018-03-27 09:29
@D0ve 
It would be possible to do so using Termux, also make a shortcut using Tasker, but that's not what I'm saying (also impossible to use when eg. clicking on links in other apps)

**Comment by D0ve** [comment] 2018-03-27 10:52
Still we wait promised extensions support  , I would suggest an issue ,- one file in app user folder which conteins start  command line parameters.

**Comment by flamsmark** [comment] 2018-04-02 20:33
Duplicate of #130.

**Closed by flamsmark** 2018-04-02 20:33 UTC
